# CMake generated Testfile for 
# Source directory: D:/Repos/OpenAvnu/testing
# Build directory: D:/Repos/OpenAvnu/build_verify/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(AvnuAllianceGptp "D:/Repos/OpenAvnu/build_verify/testing/conformance/avnu_alliance/gptp/clock_quality/Debug/clock_quality_tests_consolidated.exe")
  set_tests_properties(AvnuAllianceGptp PROPERTIES  LABELS "conformance;avnu;gptp" TIMEOUT "60" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/conformance/avnu_alliance/gptp/clock_quality" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;29;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(AvnuAllianceGptp "D:/Repos/OpenAvnu/build_verify/testing/conformance/avnu_alliance/gptp/clock_quality/Release/clock_quality_tests_consolidated.exe")
  set_tests_properties(AvnuAllianceGptp PROPERTIES  LABELS "conformance;avnu;gptp" TIMEOUT "60" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/conformance/avnu_alliance/gptp/clock_quality" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;29;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(AvnuAllianceGptp "D:/Repos/OpenAvnu/build_verify/testing/conformance/avnu_alliance/gptp/clock_quality/MinSizeRel/clock_quality_tests_consolidated.exe")
  set_tests_properties(AvnuAllianceGptp PROPERTIES  LABELS "conformance;avnu;gptp" TIMEOUT "60" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/conformance/avnu_alliance/gptp/clock_quality" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;29;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(AvnuAllianceGptp "D:/Repos/OpenAvnu/build_verify/testing/conformance/avnu_alliance/gptp/clock_quality/RelWithDebInfo/clock_quality_tests_consolidated.exe")
  set_tests_properties(AvnuAllianceGptp PROPERTIES  LABELS "conformance;avnu;gptp" TIMEOUT "60" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/conformance/avnu_alliance/gptp/clock_quality" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;29;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
else()
  add_test(AvnuAllianceGptp NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Phase2Integration "D:/Repos/OpenAvnu/build_verify/testing/integration/phase2/Debug/test_phase2_backend_integration_consolidated.exe")
  set_tests_properties(Phase2Integration PROPERTIES  LABELS "integration;phase2" TIMEOUT "180" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/integration/phase2" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;75;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Phase2Integration "D:/Repos/OpenAvnu/build_verify/testing/integration/phase2/Release/test_phase2_backend_integration_consolidated.exe")
  set_tests_properties(Phase2Integration PROPERTIES  LABELS "integration;phase2" TIMEOUT "180" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/integration/phase2" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;75;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Phase2Integration "D:/Repos/OpenAvnu/build_verify/testing/integration/phase2/MinSizeRel/test_phase2_backend_integration_consolidated.exe")
  set_tests_properties(Phase2Integration PROPERTIES  LABELS "integration;phase2" TIMEOUT "180" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/integration/phase2" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;75;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Phase2Integration "D:/Repos/OpenAvnu/build_verify/testing/integration/phase2/RelWithDebInfo/test_phase2_backend_integration_consolidated.exe")
  set_tests_properties(Phase2Integration PROPERTIES  LABELS "integration;phase2" TIMEOUT "180" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/integration/phase2" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;75;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
else()
  add_test(Phase2Integration NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Phase3Production "D:/Repos/OpenAvnu/build_verify/testing/integration/phase3/Debug/phase3_production_test_consolidated.exe")
  set_tests_properties(Phase3Production PROPERTIES  LABELS "integration;phase3" TIMEOUT "300" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/integration/phase3" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;82;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Phase3Production "D:/Repos/OpenAvnu/build_verify/testing/integration/phase3/Release/phase3_production_test_consolidated.exe")
  set_tests_properties(Phase3Production PROPERTIES  LABELS "integration;phase3" TIMEOUT "300" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/integration/phase3" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;82;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Phase3Production "D:/Repos/OpenAvnu/build_verify/testing/integration/phase3/MinSizeRel/phase3_production_test_consolidated.exe")
  set_tests_properties(Phase3Production PROPERTIES  LABELS "integration;phase3" TIMEOUT "300" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/integration/phase3" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;82;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Phase3Production "D:/Repos/OpenAvnu/build_verify/testing/integration/phase3/RelWithDebInfo/phase3_production_test_consolidated.exe")
  set_tests_properties(Phase3Production PROPERTIES  LABELS "integration;phase3" TIMEOUT "300" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing/integration/phase3" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;82;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
else()
  add_test(Phase3Production NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(AVTPProfileValidation "D:/Repos/OpenAvnu/build_verify/testing/Debug/test_avtp_profile_validation.exe")
  set_tests_properties(AVTPProfileValidation PROPERTIES  LABELS "integration;avtp;profiles" TIMEOUT "60" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;89;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(AVTPProfileValidation "D:/Repos/OpenAvnu/build_verify/testing/Release/test_avtp_profile_validation.exe")
  set_tests_properties(AVTPProfileValidation PROPERTIES  LABELS "integration;avtp;profiles" TIMEOUT "60" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;89;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(AVTPProfileValidation "D:/Repos/OpenAvnu/build_verify/testing/MinSizeRel/test_avtp_profile_validation.exe")
  set_tests_properties(AVTPProfileValidation PROPERTIES  LABELS "integration;avtp;profiles" TIMEOUT "60" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;89;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(AVTPProfileValidation "D:/Repos/OpenAvnu/build_verify/testing/RelWithDebInfo/test_avtp_profile_validation.exe")
  set_tests_properties(AVTPProfileValidation PROPERTIES  LABELS "integration;avtp;profiles" TIMEOUT "60" WORKING_DIRECTORY "D:/Repos/OpenAvnu/build_verify/testing" _BACKTRACE_TRIPLES "D:/Repos/OpenAvnu/testing/CMakeLists.txt;89;add_test;D:/Repos/OpenAvnu/testing/CMakeLists.txt;0;")
else()
  add_test(AVTPProfileValidation NOT_AVAILABLE)
endif()
subdirs("conformance/avnu_alliance/gptp/clock_quality")
subdirs("integration/phase2")
subdirs("integration/phase3")
subdirs("performance")
