version: '1.0.{build}'

clone_folder: c:\oavb
clone_depth: 20

environment:
  # Config for mrp Windows build
  WPCAP_DIR: c:\oavb\npcap-sdk
  
install:
  - git submodule update --init --recursive
  # download Npcap developer pack and unzip it
  - ps: Start-FileDownload 'https://npcap.com/dist/npcap-sdk.zip'
  - ps: 7z x npcap-sdk.zip

before_build:
  # cmake
  - choco upgrade cmake
  - set path=C:\Program Files\CMake\bin;%path%

build_script:
  - cd c:\oavb
  - cmake CMakeLists.txt -G "Visual Studio 12 2013"
  - cmake --build . --config Release
