# Install script for directory: D:/Repos/OpenAvnu/lib/la_avdecc/src

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/Install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/Debug/la_avdecc_cxx-d.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/Release/la_avdecc_cxx.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/MinSizeRel/la_avdecc_cxx.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/RelWithDebInfo/la_avdecc_cxx.lib")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/Debug/la_avdecc_cxx-d.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/Release/la_avdecc_cxx.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/MinSizeRel/la_avdecc_cxx.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/RelWithDebInfo/la_avdecc_cxx.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/cmake/la_avdecc_cxx.cmake")
    file(DIFFERENT _cmake_export_file_changed FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/cmake/la_avdecc_cxx.cmake"
         "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/CMakeFiles/Export/272ceadb8458515b2ae4b5630a6029cc/la_avdecc_cxx.cmake")
    if(_cmake_export_file_changed)
      file(GLOB _cmake_old_config_files "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/cmake/la_avdecc_cxx-*.cmake")
      if(_cmake_old_config_files)
        string(REPLACE ";" ", " _cmake_old_config_files_text "${_cmake_old_config_files}")
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/cmake/la_avdecc_cxx.cmake\" will be replaced.  Removing files [${_cmake_old_config_files_text}].")
        unset(_cmake_old_config_files_text)
        file(REMOVE ${_cmake_old_config_files})
      endif()
      unset(_cmake_old_config_files)
    endif()
    unset(_cmake_export_file_changed)
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/cmake" TYPE FILE FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/CMakeFiles/Export/272ceadb8458515b2ae4b5630a6029cc/la_avdecc_cxx.cmake")
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/cmake" TYPE FILE FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/CMakeFiles/Export/272ceadb8458515b2ae4b5630a6029cc/la_avdecc_cxx-debug.cmake")
  endif()
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/cmake" TYPE FILE FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/CMakeFiles/Export/272ceadb8458515b2ae4b5630a6029cc/la_avdecc_cxx-minsizerel.cmake")
  endif()
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/cmake" TYPE FILE FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/CMakeFiles/Export/272ceadb8458515b2ae4b5630a6029cc/la_avdecc_cxx-relwithdebinfo.cmake")
  endif()
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/cmake" TYPE FILE FILES "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/CMakeFiles/Export/272ceadb8458515b2ae4b5630a6029cc/la_avdecc_cxx-release.cmake")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/avdecc.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/executor.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/logger.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/memoryBuffer.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/utils.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/watchDog.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/aggregateEntity.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/controllerEntity.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/endian.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/endStation.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entity.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityAddressAccessTypes.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityEnums.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityModel.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityModelControlValues.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityModelControlValuesTraits.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityModelTree.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityModelTreeCommon.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityModelTreeDynamic.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityModelTreeStatic.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/entityModelTypes.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/exception.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/exports.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/instrumentationNotifier.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/jsonSerialization.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/logItems.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolAaAecpdu.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolAcmpdu.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolAdpdu.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolAecpdu.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolAemAecpdu.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolAemPayloadSizes.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolAvtpdu.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolDefines.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolMvuAecpdu.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolMvuPayloadSizes.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolVuAecpdu.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/protocolInterface.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/serialization.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/streamFormatInfo.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/uniqueIdentifier.hpp")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "LA_avdecc" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee]|[Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/la/avdecc/internals" TYPE FILE FILES "D:/Repos/OpenAvnu/lib/la_avdecc/include/la/avdecc/internals/jsonTypes.hpp")
  endif()
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "D:/Repos/OpenAvnu/build_verify/lib/la_avdecc/src/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
