name: Manual Test on DAW02

on:
  workflow_dispatch:

jobs:
  build-and-hwtest:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Run Integration & Hardware Tests
        run: cmake --build build --config Release --target RUN_TESTS

      - name: I225 Register Hardware Test
        shell: pwsh
        run: |
          ./test_i225_register_access.ps1 -Verbose -SaveLog -LogPath "docs/tests/results/i225_register_test_${{ github.run_id }}.log"

      - name: Timestamp Automated Test Suite
        run: |
          python tools/timestamp_analysis/automated_test_suite.py --verbose --output docs/tests/results/automated_test_suite_${{ github.run_id }}.json

      - name: Timestamp Analysis (optional)
        run: |
          python tools/timestamp_analysis/timestamp_analyzer.py --duration 300 --output docs/tests/results/timestamp_analysis_${{ github.run_id }}.json
        continue-on-error: true

      - name: Collect Test Results
        run: |
          mkdir -Force -Path docs/tests/results
          if (Test-Path build/Testing/Temporary/LastTest.log) {
            Copy-Item build/Testing/Temporary/LastTest.log docs/tests/results/LastTest_${{ github.run_id }}.log
          }
          # Weitere Logfiles oder Hardware-Reports können hier gesammelt werden

      - name: Collect System Info
        run: |
          mkdir -Force -Path docs/machine
          systeminfo > docs/machine/DAW02_systeminfo_${{ github.run_id }}.txt
          Get-WmiObject Win32_NetworkAdapter | Out-File docs/machine/DAW02_networkadapters_${{ github.run_id }}.txt
